/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'status' : PostStatus,
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : [] | [string],
  'excerpt' : string,
}
export interface CMSSetting { 'key' : string, 'value' : string }
export interface ContactMessage {
  'id' : string,
  'subject' : string,
  'name' : string,
  'createdAt' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export interface Experience {
  'id' : string,
  'endDate' : [] | [string],
  'order' : bigint,
  'role' : string,
  'description' : string,
  'company' : string,
  'current' : boolean,
  'location' : string,
  'startDate' : string,
}
export type ExternalBlob = Uint8Array;
export type PostStatus = { 'published' : null } |
  { 'draft' : null };
export interface Project {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'order' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'githubUrl' : [] | [string],
  'imageUrl' : string,
  'shortDesc' : string,
  'category' : ProjectCategory,
  'liveUrl' : [] | [string],
}
export type ProjectCategory = { 'web' : null } |
  { 'other' : null } |
  { 'design' : null } |
  { 'mobile' : null };
export interface Service {
  'id' : string,
  'title' : string,
  'features' : Array<string>,
  'order' : bigint,
  'icon' : string,
  'description' : string,
  'price' : [] | [string],
}
export interface Skill {
  'id' : string,
  'icon' : string,
  'name' : string,
  'category' : SkillCategory,
  'percentage' : bigint,
}
export type SkillCategory = { 'other' : null } |
  { 'frontend' : null } |
  { 'design' : null } |
  { 'backend' : null };
export interface Testimonial {
  'id' : string,
  'featured' : boolean,
  'name' : string,
  'role' : string,
  'text' : string,
  'company' : string,
  'avatarUrl' : string,
  'rating' : bigint,
}
export interface Theme {
  'primaryColor' : string,
  'accentColor' : string,
  'secondaryColor' : string,
  'textColor' : string,
  'bgColor' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addImageReference' : ActorMethod<[string, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'createBlogPost' : ActorMethod<[BlogPost], string>,
  'createExperience' : ActorMethod<[Experience], string>,
  'createProject' : ActorMethod<[Project], string>,
  'createService' : ActorMethod<[Service], string>,
  'createSkill' : ActorMethod<[Skill], string>,
  'createTestimonial' : ActorMethod<[Testimonial], string>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteExperience' : ActorMethod<[string], undefined>,
  'deleteImageReference' : ActorMethod<[string], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteSkill' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getAllImageReferences' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getAllSettings' : ActorMethod<[], Array<CMSSetting>>,
  'getBlogPostById' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExperienceById' : ActorMethod<[string], [] | [Experience]>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getImageReference' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getProjectById' : ActorMethod<[string], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getPublishedPosts' : ActorMethod<[], Array<BlogPost>>,
  'getServiceById' : ActorMethod<[string], [] | [Service]>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSetting' : ActorMethod<[string], [] | [string]>,
  'getSkillById' : ActorMethod<[string], [] | [Skill]>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'getTestimonialById' : ActorMethod<[string], [] | [Testimonial]>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTheme' : ActorMethod<[], Theme>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContact' : ActorMethod<[ContactMessage], string>,
  'updateBlogPost' : ActorMethod<[string, BlogPost], undefined>,
  'updateExperience' : ActorMethod<[string, Experience], undefined>,
  'updateProject' : ActorMethod<[string, Project], undefined>,
  'updateService' : ActorMethod<[string, Service], undefined>,
  'updateSetting' : ActorMethod<[string, string], undefined>,
  'updateSkill' : ActorMethod<[string, Skill], undefined>,
  'updateTestimonial' : ActorMethod<[string, Testimonial], undefined>,
  'updateTheme' : ActorMethod<[Theme], undefined>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];