/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'status' : PostStatus,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'order' : IDL.Nat,
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'current' : IDL.Bool,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const ProjectCategory = IDL.Variant({
  'web' : IDL.Null,
  'other' : IDL.Null,
  'design' : IDL.Null,
  'mobile' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'order' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'githubUrl' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'shortDesc' : IDL.Text,
  'category' : ProjectCategory,
  'liveUrl' : IDL.Opt(IDL.Text),
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Opt(IDL.Text),
});
export const SkillCategory = IDL.Variant({
  'other' : IDL.Null,
  'frontend' : IDL.Null,
  'design' : IDL.Null,
  'backend' : IDL.Null,
});
export const Skill = IDL.Record({
  'id' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'category' : SkillCategory,
  'percentage' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'text' : IDL.Text,
  'company' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const CMSSetting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Theme = IDL.Record({
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'textColor' : IDL.Text,
  'bgColor' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImageReference' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'createBlogPost' : IDL.Func([BlogPost], [IDL.Text], []),
  'createExperience' : IDL.Func([Experience], [IDL.Text], []),
  'createProject' : IDL.Func([Project], [IDL.Text], []),
  'createService' : IDL.Func([Service], [IDL.Text], []),
  'createSkill' : IDL.Func([Skill], [IDL.Text], []),
  'createTestimonial' : IDL.Func([Testimonial], [IDL.Text], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteExperience' : IDL.Func([IDL.Text], [], []),
  'deleteImageReference' : IDL.Func([IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'deleteSkill' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'getAllImageReferences' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getAllSettings' : IDL.Func([], [IDL.Vec(CMSSetting)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExperienceById' : IDL.Func([IDL.Text], [IDL.Opt(Experience)], ['query']),
  'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getImageReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getProjectById' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getServiceById' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSkillById' : IDL.Func([IDL.Text], [IDL.Opt(Skill)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getTestimonialById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Testimonial)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTheme' : IDL.Func([], [Theme], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContact' : IDL.Func([ContactMessage], [IDL.Text], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
  'updateExperience' : IDL.Func([IDL.Text, Experience], [], []),
  'updateProject' : IDL.Func([IDL.Text, Project], [], []),
  'updateService' : IDL.Func([IDL.Text, Service], [], []),
  'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSkill' : IDL.Func([IDL.Text, Skill], [], []),
  'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'updateTheme' : IDL.Func([Theme], [], []),
  'verifyAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'status' : PostStatus,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'order' : IDL.Nat,
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'current' : IDL.Bool,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const ProjectCategory = IDL.Variant({
    'web' : IDL.Null,
    'other' : IDL.Null,
    'design' : IDL.Null,
    'mobile' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'order' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'githubUrl' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'shortDesc' : IDL.Text,
    'category' : ProjectCategory,
    'liveUrl' : IDL.Opt(IDL.Text),
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Opt(IDL.Text),
  });
  const SkillCategory = IDL.Variant({
    'other' : IDL.Null,
    'frontend' : IDL.Null,
    'design' : IDL.Null,
    'backend' : IDL.Null,
  });
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'category' : SkillCategory,
    'percentage' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'text' : IDL.Text,
    'company' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const CMSSetting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Theme = IDL.Record({
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'textColor' : IDL.Text,
    'bgColor' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImageReference' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'createBlogPost' : IDL.Func([BlogPost], [IDL.Text], []),
    'createExperience' : IDL.Func([Experience], [IDL.Text], []),
    'createProject' : IDL.Func([Project], [IDL.Text], []),
    'createService' : IDL.Func([Service], [IDL.Text], []),
    'createSkill' : IDL.Func([Skill], [IDL.Text], []),
    'createTestimonial' : IDL.Func([Testimonial], [IDL.Text], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteExperience' : IDL.Func([IDL.Text], [], []),
    'deleteImageReference' : IDL.Func([IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'deleteSkill' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'getAllImageReferences' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getAllSettings' : IDL.Func([], [IDL.Vec(CMSSetting)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExperienceById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Experience)],
        ['query'],
      ),
    'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getImageReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getProjectById' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getServiceById' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getSkillById' : IDL.Func([IDL.Text], [IDL.Opt(Skill)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getTestimonialById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Testimonial)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTheme' : IDL.Func([], [Theme], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContact' : IDL.Func([ContactMessage], [IDL.Text], []),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
    'updateExperience' : IDL.Func([IDL.Text, Experience], [], []),
    'updateProject' : IDL.Func([IDL.Text, Project], [], []),
    'updateService' : IDL.Func([IDL.Text, Service], [], []),
    'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSkill' : IDL.Func([IDL.Text, Skill], [], []),
    'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'updateTheme' : IDL.Func([Theme], [], []),
    'verifyAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };