/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: string;
    featured: boolean;
    name: string;
    role: string;
    text: string;
    company: string;
    avatarUrl: string;
    rating: bigint;
}
export interface BlogPost {
    id: string;
    status: PostStatus;
    coverImageUrl: string;
    title: string;
    content: string;
    slug: string;
    tags: Array<string>;
    publishedAt?: string;
    excerpt: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: string;
    title: string;
    features: Array<string>;
    order: bigint;
    icon: string;
    description: string;
    price?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CMSSetting {
    key: string;
    value: string;
}
export interface ContactMessage {
    id: string;
    subject: string;
    name: string;
    createdAt: string;
    isRead: boolean;
    email: string;
    message: string;
}
export interface Skill {
    id: string;
    icon: string;
    name: string;
    category: SkillCategory;
    percentage: bigint;
}
export interface Experience {
    id: string;
    endDate?: string;
    order: bigint;
    role: string;
    description: string;
    company: string;
    current: boolean;
    location: string;
    startDate: string;
}
export interface Project {
    id: string;
    title: string;
    featured: boolean;
    order: bigint;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    imageUrl: string;
    shortDesc: string;
    category: ProjectCategory;
    liveUrl?: string;
}
export interface Theme {
    primaryColor: string;
    accentColor: string;
    secondaryColor: string;
    textColor: string;
    bgColor: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PostStatus {
    published = "published",
    draft = "draft"
}
export enum ProjectCategory {
    web = "web",
    other = "other",
    design = "design",
    mobile = "mobile"
}
export enum SkillCategory {
    other = "other",
    frontend = "frontend",
    design = "design",
    backend = "backend"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addImageReference(id: string, blob: ExternalBlob): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
    createBlogPost(post: BlogPost): Promise<string>;
    createExperience(exp: Experience): Promise<string>;
    createProject(project: Project): Promise<string>;
    createService(service: Service): Promise<string>;
    createSkill(skill: Skill): Promise<string>;
    createTestimonial(testimonial: Testimonial): Promise<string>;
    deleteBlogPost(id: string): Promise<void>;
    deleteExperience(id: string): Promise<void>;
    deleteImageReference(id: string): Promise<void>;
    deleteMessage(id: string): Promise<void>;
    deleteProject(id: string): Promise<void>;
    deleteService(id: string): Promise<void>;
    deleteSkill(id: string): Promise<void>;
    deleteTestimonial(id: string): Promise<void>;
    getAllImageReferences(): Promise<Array<[string, ExternalBlob]>>;
    getAllSettings(): Promise<Array<CMSSetting>>;
    getBlogPostById(id: string): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExperienceById(id: string): Promise<Experience | null>;
    getExperiences(): Promise<Array<Experience>>;
    getFeaturedProjects(): Promise<Array<Project>>;
    getImageReference(id: string): Promise<ExternalBlob | null>;
    getMessages(): Promise<Array<ContactMessage>>;
    getPostBySlug(slug: string): Promise<BlogPost | null>;
    getProjectById(id: string): Promise<Project | null>;
    getProjects(): Promise<Array<Project>>;
    getPublishedPosts(): Promise<Array<BlogPost>>;
    getServiceById(id: string): Promise<Service | null>;
    getServices(): Promise<Array<Service>>;
    getSetting(key: string): Promise<string | null>;
    getSkillById(id: string): Promise<Skill | null>;
    getSkills(): Promise<Array<Skill>>;
    getTestimonialById(id: string): Promise<Testimonial | null>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getTheme(): Promise<Theme>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAsRead(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContact(message: ContactMessage): Promise<string>;
    updateBlogPost(id: string, post: BlogPost): Promise<void>;
    updateExperience(id: string, exp: Experience): Promise<void>;
    updateProject(id: string, project: Project): Promise<void>;
    updateService(id: string, service: Service): Promise<void>;
    updateSetting(key: string, value: string): Promise<void>;
    updateSkill(id: string, skill: Skill): Promise<void>;
    updateTestimonial(id: string, testimonial: Testimonial): Promise<void>;
    updateTheme(newTheme: Theme): Promise<void>;
    verifyAdminCredentials(username: string, password: string): Promise<boolean>;
}
import type { BlogPost as _BlogPost, Experience as _Experience, ExternalBlob as _ExternalBlob, PostStatus as _PostStatus, Project as _Project, ProjectCategory as _ProjectCategory, Service as _Service, Skill as _Skill, SkillCategory as _SkillCategory, Testimonial as _Testimonial, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addImageReference(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addImageReference(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImageReference(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async createBlogPost(arg0: BlogPost): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createExperience(arg0: Experience): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createExperience(to_candid_Experience_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExperience(to_candid_Experience_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProject(arg0: Project): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_Project_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_Project_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createService(arg0: Service): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_Service_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_Service_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSkill(arg0: Skill): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSkill(to_candid_Skill_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSkill(to_candid_Skill_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTestimonial(arg0: Testimonial): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteExperience(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperience(arg0);
            return result;
        }
    }
    async deleteImageReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImageReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImageReference(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteService(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async deleteSkill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSkill(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getAllImageReferences(): Promise<Array<[string, ExternalBlob]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImageReferences();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImageReferences();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSettings(): Promise<Array<CMSSetting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSettings();
            return result;
        }
    }
    async getBlogPostById(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperienceById(arg0: string): Promise<Experience | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperienceById(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperienceById(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiences();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiences();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProjects();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProjects();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImageReference(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImageReference(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImageReference(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostBySlug(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostBySlug(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectById(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectById(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectById(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPosts();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPosts();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceById(arg0: string): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceById(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceById(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetting(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetting(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetting(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkillById(arg0: string): Promise<Skill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillById(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillById(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkills();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkills();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialById(arg0: string): Promise<Testimonial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialById(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialById(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getTheme(): Promise<Theme> {
        if (this.processError) {
            try {
                const result = await this.actor.getTheme();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTheme();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContact(arg0: ContactMessage): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateExperience(arg0: string, arg1: Experience): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperience(arg0, to_candid_Experience_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperience(arg0, to_candid_Experience_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProject(arg0: string, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_Project_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_Project_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: string, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, to_candid_Service_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, to_candid_Service_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSetting(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSetting(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSetting(arg0, arg1);
            return result;
        }
    }
    async updateSkill(arg0: string, arg1: Skill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkill(arg0, to_candid_Skill_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkill(arg0, to_candid_Skill_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTestimonial(arg0: string, arg1: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, arg1);
            return result;
        }
    }
    async updateTheme(arg0: Theme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTheme(arg0);
            return result;
        }
    }
    async verifyAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BlogPost_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Experience_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experience): Experience {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PostStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectCategory_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectCategory): ProjectCategory {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_SkillCategory_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillCategory): SkillCategory {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Experience]): Experience | null {
    return value.length === 0 ? null : from_candid_Experience_n40(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Skill]): Skill | null {
    return value.length === 0 ? null : from_candid_Skill_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Testimonial]): Testimonial | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PostStatus;
    coverImageUrl: string;
    title: string;
    content: string;
    slug: string;
    tags: Array<string>;
    publishedAt: [] | [string];
    excerpt: string;
}): {
    id: string;
    status: PostStatus;
    coverImageUrl: string;
    title: string;
    content: string;
    slug: string;
    tags: Array<string>;
    publishedAt?: string;
    excerpt: string;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n33(_uploadFile, _downloadFile, value.status),
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        content: value.content,
        slug: value.slug,
        tags: value.tags,
        publishedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.publishedAt)),
        excerpt: value.excerpt
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [string];
    order: bigint;
    role: string;
    description: string;
    company: string;
    current: boolean;
    location: string;
    startDate: string;
}): {
    id: string;
    endDate?: string;
    order: bigint;
    role: string;
    description: string;
    company: string;
    current: boolean;
    location: string;
    startDate: string;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.endDate)),
        order: value.order,
        role: value.role,
        description: value.description,
        company: value.company,
        current: value.current,
        location: value.location,
        startDate: value.startDate
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    featured: boolean;
    order: bigint;
    tags: Array<string>;
    description: string;
    githubUrl: [] | [string];
    imageUrl: string;
    shortDesc: string;
    category: _ProjectCategory;
    liveUrl: [] | [string];
}): {
    id: string;
    title: string;
    featured: boolean;
    order: bigint;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    imageUrl: string;
    shortDesc: string;
    category: ProjectCategory;
    liveUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        order: value.order,
        tags: value.tags,
        description: value.description,
        githubUrl: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.githubUrl)),
        imageUrl: value.imageUrl,
        shortDesc: value.shortDesc,
        category: from_candid_ProjectCategory_n46(_uploadFile, _downloadFile, value.category),
        liveUrl: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.liveUrl))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    features: Array<string>;
    order: bigint;
    icon: string;
    description: string;
    price: [] | [string];
}): {
    id: string;
    title: string;
    features: Array<string>;
    order: bigint;
    icon: string;
    description: string;
    price?: string;
} {
    return {
        id: value.id,
        title: value.title,
        features: value.features,
        order: value.order,
        icon: value.icon,
        description: value.description,
        price: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.price))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    icon: string;
    name: string;
    category: _SkillCategory;
    percentage: bigint;
}): {
    id: string;
    icon: string;
    name: string;
    category: SkillCategory;
    percentage: bigint;
} {
    return {
        id: value.id,
        icon: value.icon,
        name: value.name,
        category: from_candid_SkillCategory_n58(_uploadFile, _downloadFile, value.category),
        percentage: value.percentage
    };
}
async function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExternalBlob]): Promise<[string, ExternalBlob]> {
    return [
        value[0],
        await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): PostStatus {
    return "published" in value ? PostStatus.published : "draft" in value ? PostStatus.draft : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    web: null;
} | {
    other: null;
} | {
    design: null;
} | {
    mobile: null;
}): ProjectCategory {
    return "web" in value ? ProjectCategory.web : "other" in value ? ProjectCategory.other : "design" in value ? ProjectCategory.design : "mobile" in value ? ProjectCategory.mobile : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    frontend: null;
} | {
    design: null;
} | {
    backend: null;
}): SkillCategory {
    return "other" in value ? SkillCategory.other : "frontend" in value ? SkillCategory.frontend : "design" in value ? SkillCategory.design : "backend" in value ? SkillCategory.backend : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExternalBlob]>): Promise<Array<[string, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Experience>): Array<Experience> {
    return value.map((x)=>from_candid_Experience_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n56(_uploadFile, _downloadFile, x));
}
function to_candid_BlogPost_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPost): _BlogPost {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Experience_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Experience): _Experience {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PostStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): _ProjectCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_SkillCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillCategory): _SkillCategory {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Skill_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): _Skill {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: PostStatus;
    coverImageUrl: string;
    title: string;
    content: string;
    slug: string;
    tags: Array<string>;
    publishedAt?: string;
    excerpt: string;
}): {
    id: string;
    status: _PostStatus;
    coverImageUrl: string;
    title: string;
    content: string;
    slug: string;
    tags: Array<string>;
    publishedAt: [] | [string];
    excerpt: string;
} {
    return {
        id: value.id,
        status: to_candid_PostStatus_n13(_uploadFile, _downloadFile, value.status),
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        content: value.content,
        slug: value.slug,
        tags: value.tags,
        publishedAt: value.publishedAt ? candid_some(value.publishedAt) : candid_none(),
        excerpt: value.excerpt
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate?: string;
    order: bigint;
    role: string;
    description: string;
    company: string;
    current: boolean;
    location: string;
    startDate: string;
}): {
    id: string;
    endDate: [] | [string];
    order: bigint;
    role: string;
    description: string;
    company: string;
    current: boolean;
    location: string;
    startDate: string;
} {
    return {
        id: value.id,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        order: value.order,
        role: value.role,
        description: value.description,
        company: value.company,
        current: value.current,
        location: value.location,
        startDate: value.startDate
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    featured: boolean;
    order: bigint;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    imageUrl: string;
    shortDesc: string;
    category: ProjectCategory;
    liveUrl?: string;
}): {
    id: string;
    title: string;
    featured: boolean;
    order: bigint;
    tags: Array<string>;
    description: string;
    githubUrl: [] | [string];
    imageUrl: string;
    shortDesc: string;
    category: _ProjectCategory;
    liveUrl: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        order: value.order,
        tags: value.tags,
        description: value.description,
        githubUrl: value.githubUrl ? candid_some(value.githubUrl) : candid_none(),
        imageUrl: value.imageUrl,
        shortDesc: value.shortDesc,
        category: to_candid_ProjectCategory_n19(_uploadFile, _downloadFile, value.category),
        liveUrl: value.liveUrl ? candid_some(value.liveUrl) : candid_none()
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    features: Array<string>;
    order: bigint;
    icon: string;
    description: string;
    price?: string;
}): {
    id: string;
    title: string;
    features: Array<string>;
    order: bigint;
    icon: string;
    description: string;
    price: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        features: value.features,
        order: value.order,
        icon: value.icon,
        description: value.description,
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    icon: string;
    name: string;
    category: SkillCategory;
    percentage: bigint;
}): {
    id: string;
    icon: string;
    name: string;
    category: _SkillCategory;
    percentage: bigint;
} {
    return {
        id: value.id,
        icon: value.icon,
        name: value.name,
        category: to_candid_SkillCategory_n25(_uploadFile, _downloadFile, value.category),
        percentage: value.percentage
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == PostStatus.published ? {
        published: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): {
    web: null;
} | {
    other: null;
} | {
    design: null;
} | {
    mobile: null;
} {
    return value == ProjectCategory.web ? {
        web: null
    } : value == ProjectCategory.other ? {
        other: null
    } : value == ProjectCategory.design ? {
        design: null
    } : value == ProjectCategory.mobile ? {
        mobile: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillCategory): {
    other: null;
} | {
    frontend: null;
} | {
    design: null;
} | {
    backend: null;
} {
    return value == SkillCategory.other ? {
        other: null
    } : value == SkillCategory.frontend ? {
        frontend: null
    } : value == SkillCategory.design ? {
        design: null
    } : value == SkillCategory.backend ? {
        backend: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
